/*
 * Copyright (c) 2026 Prowide Inc.
 * All rights reserved. This program and the accompanying materials are made available under the terms of private
 * license agreements between Prowide Inc. and its commercial customers and partners.
 */
package com.prowidesoftware.swift.samples.integrator.myformat;

import com.prowidesoftware.swift.myformat.FileFormat;
import com.prowidesoftware.swift.myformat.MappingTable;
import com.prowidesoftware.swift.myformat.MappingTableDatabaseLoader;
import com.prowidesoftware.swift.myformat.MyFormatEngine;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * This example loads a mapping table from a database, the recommended setup when the mappings must
 * be maintained at runtime without redeploying the application.
 * <p>
 * The default table name is {@code pw_mapping_rule} with the same four columns of the spreadsheet
 * layout plus a configuration name and an order; several mapping configurations can share the
 * table. Custom table and column names are supported through the loader setters, and DDL scripts
 * for the common database engines are available in the MyFormat documentation.
 * <p>
 * An embedded in-memory Derby database is created on the fly here to keep the example self
 * contained; in a real application the loader is created from your connection, DataSource or JNDI
 * name.
 *
 * @since 9.1.8
 */
public class MappingTableDatabaseExample {

    public static final String sample = "{\n"
            + "  \"reference\": \"REF20260817\",\n"
            + "  \"amount\": { \"currency\": \"EUR\", \"value\": \"50000.00\" },\n"
            + "  \"date\": \"2026-08-18\"\n"
            + "}";

    public static void main(String[] args) throws SQLException {
        try (Connection connection = DriverManager.getConnection("jdbc:derby:memory:myformat;create=true")) {
            createMappingRules(connection);

            MappingTableDatabaseLoader loader = new MappingTableDatabaseLoader(connection);
            MappingTable table = loader.load("json2mt202", FileFormat.JSON, FileFormat.MT);

            if (!loader.getProblems().isEmpty()) {
                System.out.println("Problems loading the table: " + loader.getProblems());
                return;
            }
            System.out.println(table.getRules().size() + " rules loaded from database");

            System.out.println(MyFormatEngine.translate(sample, table));
        }
    }

    private static void createMappingRules(Connection connection) throws SQLException {
        try (Statement statement = connection.createStatement()) {
            statement.execute("create table pw_mapping_rule ("
                    + "id bigint generated by default as identity,"
                    + "pw_conf_name varchar(50) not null,"
                    + "pw_order integer not null,"
                    + "pw_source varchar(255) not null,"
                    + "pw_transformation varchar(255),"
                    + "pw_target varchar(100) not null,"
                    + "pw_mode varchar(20),"
                    + "primary key (id))");
        }
        String[][] rules = {
            {"MT202", null, "mtType", "SETUP"},
            {"reference", null, "20", null},
            {"date", "formatDateTime(\"yyyy-MM-dd\",\"yyMMdd\")", "32A/1", "UPDATE"},
            {"amount.currency", null, "32A/2", "UPDATE"},
            {"amount.value", "formatMTDecimal()", "32A/3", "UPDATE"}
        };
        try (PreparedStatement insert = connection.prepareStatement(
                "insert into pw_mapping_rule (pw_conf_name, pw_order, pw_source, pw_transformation, pw_target, pw_mode)"
                        + " values ('json2mt202', ?, ?, ?, ?, ?)")) {
            for (int i = 0; i < rules.length; i++) {
                insert.setInt(1, i);
                insert.setString(2, rules[i][0]);
                insert.setString(3, rules[i][1]);
                insert.setString(4, rules[i][2]);
                insert.setString(5, rules[i][3]);
                insert.executeUpdate();
            }
        }
    }
}
